# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 13:03
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=core.models.content_file_name)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'uploaded_at',
            },
        ),
    ]
